name: cli-jobs-pipelines-nyc-taxi-pipeline
on:
  workflow_dispatch:
env:
  SUBSCRIPTION_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
  RESOURCE_GROUP_NAME: ${{ secrets.SERVICE_PRINCIPAL_ID }}
  WORKSPACE_NAME:  ${{ secrets.SERVICE_PRINCIPAL_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZUREML_CREDENTIALS}}
    - name: bootstrap resources
      run: |
          echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}';
          bash bootstrap.sh
      working-directory: infra/bootstrapping
      continue-on-error: false
    - name: setup-cli
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run job
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          bash -x ../../../run-job.sh pipeline.yml
      working-directory: cli/jobs/pipelines/nyc-taxi
    - name: validate readme
      run: |
          python check-readme.py "${{ github.workspace }}/cli/jobs/pipelines/nyc-taxi"
      working-directory: infra/bootstrapping
      continue-on-error: false
