name: cli-jobs-single-step-bank-data-job
on:
  workflow_dispatch:
env:
  SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
  SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP }}
  WORKSPACE_NAME:  ${{ secrets.WORKSPACE_NAME }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZUREML_CREDENTIALS}}
    - name: bootstrap resources
      run: |
          echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}';
          bash bootstrap.sh
      working-directory: infra/bootstrapping
      continue-on-error: false
    - name: setup-cli
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run job
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          cat > ./job.yml <<EOF
          \$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
          code: model
          environment_variables:
            SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
            SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
            TENANT_ID: ${{ secrets.TENANT_ID }}
            SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
            RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
            WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}

          command: >-
            python train.py

          environment: azureml://registries/azureml/environments/AzureML-AutoML/versions/142
          compute: azureml:shared-runner-1
          experiment_name: bank-data-example
          description: Train a classification model on bank data
          EOF
          bash -x ../../../../run-job.sh job.yml
      working-directory: cli/jobs/single-step/dynamic-compute/bank-data

